---
title: "Analysis on LendingClub's Loan Data"
author: "Uyemaa Gantulga, Ayush Meshram, Aakash Singh, and Melissa Yago"
date: "10/20/24"
output:
  html_document:
    code_folding: show
    number_sections: false
    toc: yes
    toc_depth: 3
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: '3'
---

```{r setup, include=F}
# Some of common RMD options (and the defaults) are: 
# include=T, eval=T, echo=T, results='hide'/'asis'/'markup',..., collapse=F, warning=T, message=T, error=T, cache=T, fig.width=6, fig.height=4, fig.dim=c(6,4) #inches, fig.align='left'/'center','right', 
knitr::opts_chunk$set(results="markup", warning = F, message = F)
# Can globally set option for number display format.
options(scientific=T, digits = 3) 
# options(scipen=9, digits = 3) 
```

# Overview

Since 2006, LendingClub has been a U.S. financial services company that has facilitated loan contracts. Our research will focus on LendingClub's loan data that consist of approved and rejected loans between 2013-2018. To understand LendingClub’s clientele, we will analyze borrower and loan characteristics to assess risk levels, determine loan acceptance, and understand what factors influence whether accepted loans will be fully repaid. To accomplish this, we will ask the following SMART questions:


1. How do the loan features of term, amount, and interest rate influence the likelihood of a loan being charged off (lender has accepted the loan as unlikely to recover) versus being fully paid? 

2. How do the borrower characteristics of income, credit score, and application type influence/predict the likelihood of loan defaulting or being fully paid, based on historical data? 

3. Do the loan grades provided to each customer correlate to their loan repayment behavior based on income and loan status? 

4. Is there a relationship between employment length and the amount requested for rejected loans and how does it compare to the customers that had accepted loans?

# Data Dictionary

1. Funded Amount: The total amount of the loan to be paid off.

2. Loan Status: Whether the loan has been fully paid or has been charged off. A loan that is fully paid is defined as a loan where the total payment has been met. A charge off status is defined as the lender accepting the loan as uncollectible. This differs from the default status in which payments are late but the lender expects to collect what the borrower still owes.  

3. Term: How long the borrower has to pay off the loan (Either 36 or 60 Months).

4. Interest Rate: The percentage of the loan amount that the lender charges the borrower for borrowing money. 



